# Generated by Django 4.1 on 2022-08-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('trains', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название маршрута')),
                ('travel_time_total', models.PositiveSmallIntegerField(verbose_name='Общее время в пути')),
                ('from_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='from_city_total_set', to='cities.city',
                                                verbose_name='Из какого города')),
                ('to_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='to_city_total_set', to='cities.city',
                                              verbose_name='В какой город')),
                ('trains', models.ManyToManyField(to='trains.train', verbose_name='Поезда в маршруте')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['travel_time_total'],
            },
        ),
    ]
